

# Setup and Usage

The evoland-plus HPC pipeline consists out of various scripts that can be found
in the `src` directory. For each included step of @fig-pipeline, there
is a subdirectory in `src/steps`.

This part is structured as follows:

-   [Setup](setup.qmd)
-   [Steps]
    -   [LULCC](../pipeline/10_LULCC.qmd)
    -   [Check LULCC](../pipeline/11_CheckLULCC.qmd)
    -   [Focals](../pipeline/20_FocalLULC.qmd)
    -   [NCPs](../pipeline/40_NCPs.qmd)
-   [Running the pipeline](../pipeline/running.qmd)

The task of the evoland-plus HPC pipeline is to streamline the process, so that
varying the climate scenarios and other parameters can be carried out
efficiently. Introducing parallelization through
[SLURM](https://slurm.schedmd.com/overview.qmd) batch jobs, and adding
HPC compatibility, are the main tasks of the pipeline. Meanwhile, the
pipeline keeps track of the intermediate results, a centralized
configuration file, and the execution of each step. Details on the
individual steps are given in the following sections.

{{< include ../pipeline/setup.qmd >}}

## Steps
{{< include ../pipeline/10_LULCC.qmd >}}
{{< include ../pipeline/11_CheckLULCC.qmd >}}
{{< include ../pipeline/20_FocalLULC.qmd >}}
{{< include ../pipeline/40_NCPs.qmd >}}
{{< include ../pipeline/running.qmd >}}
{{< include ../50_further_steps.qmd >}}
