project:
  type: book

book:
  title: "evoland+ HPC"
  author: "Carlson Büth and Benjamin Black"
  date: "15/7/2025" # TODO: update date
  chapters:
    - index.qmd
    - intro.qmd
    - structure.qmd
    - part: pipeline/index.qmd
      chapters:
        - pipeline/setup.qmd
        - pipeline/10_LULCC.qmd
        - pipeline/11_CheckLULCC.qmd
        - pipeline/20_FocalLULC.qmd
        - pipeline/40_NCPs.qmd
        - pipeline/running.qmd
    - 50_further_steps.qmd
    - summary.qmd
    - references.qmd
  repo-url: https://github.com/cbueth/Future-EI
  issue-url: https://github.com/cbueth/Future-EI/issues/new/choose
  repo-actions: [source, issue]
  repo-subdir: FutureEiGuide
  authority: Planning of Landscape and Urban Systems – PLUS (ETH Zurich)
  language: en
  license: MIT License

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

