# Structure

For the related research project @Black2025, we couple three main
steps:
Land Use Simulation,
combined NCP Estimations and
Species Distribution Modeling.
These are shown bold in the @fig-pipeline.
Future-EI covers the LULC Simulation and steps dependent on its output,
namely the NCP estimations, intensity analysis and focal window preparation.
These steps, shown in blue, are unified to be automated for
command line interface (CLI) and high performance computing (HPC) compatibility,
to be scalable and reproducible.

```{mermaid}
%%| label: fig-pipeline
%%| fig-cap: "Pipeline Overview -- Steps in blue are part of the Future-EI pipeline, red steps are external. From this structure, a clear order of execution can be derived."
flowchart TD
  LULCC[LULCC:<br>Land Use Simulation] --> Focal(Focal LULC<br>prep.)
  LULCC --> NCP[NCP Estimation]
  LULCC --> CheckLULCC[Intensity Analysis]
  NCP --> Clust(Clustering)
  LULCC --> NSDM[N-SDM:<br>Species Distribution<br>Modelling]
  Focal --> NSDM
  NSDM --> AggSp(Species Maps Aggregation)
  AggSp --> Clust

  style LULCC color:#2780e3, fill:#e9f2fc, stroke:#000000, stroke-width:3px, font-weight:bold
  style Focal color:#2780e3, fill:#e9f2fc, stroke:#000000
  style NCP color:#2780e3, fill:#e9f2fc, stroke:#000000, stroke-width:3px, font-weight:bold
  style Clust color:#b51c89, fill:#f9e8f5, stroke:#5f5f5f
  style NSDM color:#b51c89, fill:#f9e8f5, stroke:#5f5f5f, stroke-width:3px, font-weight:bold
  style AggSp color:#b51c89, fill:#f9e8f5, stroke:#5f5f5f
```

[//]: # (TODO: Update the figure)

First, we give an overview of each step in the pipeline.
In contrast, the [Pipeline](#pipeline) section details and documents the
individual steps and code used, in terms of input, output and execution.

## LULCC: Land Use Simulation
The [land use land cover change (LULCC) model for Switzerland](https://github.com/blenback/LULCC-CH)
[@black2023;@black2024] is the first step in the Future-EI pipeline.
For given climate scenarios, it simulates land use changes in Switzerland
until a given future year (e.g., 2060),
based on historical data and future projections.
The generated land use maps are then used as input for the following steps.


## NCP: Nature Contributions to People
A range of NCP are estimated from the land use maps.
Some NCP use further data for the estimation,
e.g., precipitation and temperature projections.

The code is based on @kuelling2024,
but has been adapted for automation and HPC compatibility.


|         NCP | Name                                                   | Indicator                                        |
|------------:|--------------------------------------------------------|--------------------------------------------------|
| [CAR](#CAR) | Regulation of climate                                  | Carbon stored in biomass and soil                |
|   [FF](#FF) | Food and feed                                          | Crop production potential (`ecocrop`)            |
| [HAB](#HAB) | Habitat creation and maintenance                       | Habitat quality index                            |
| [NDR](#NDR) | Nutrient Delivery Ratio                                | Annual nutrient retention by vegetation          |
| [POL](#POL) | Pollination and dispersal of seeds                     | Habitat abundance for pollinators                |
| [REC](#REC) | Recreation potential                                   | Recreation potential (RP) provided by ecosystems |
| [SDR](#SDR) | Formation, protection and decontamination of soils     | Erosion control by sediment retention            |
|   [WY](#WY) | Regulation of freshwater quantity, location and timing | Annual water yield                               |

: Nature Contributions to People (NCP) estimated from the LULCC model.
{#tbl-ncp}


## Intensity Analysis

The Intensity Analysis (IA) is based on x,
and serves as


## Focal LULC Preparation

_Explain why_
These focal layers are used as inputs for X and Y,
and act as NCP, specifically Z.


## N-SDM: Nested Species Distribution Modelling

The [nested species distribution modelling (N-SDM)](https://github.com/N-SDM/N-SDM) [@adde2023]
step simulates the distribution of species in Switzerland.
Species occurrence used to fit models and covariate data are selected,
both at different spatial scales, to predict the species distribution.
This part is not integrated into the Future-EI pipeline,
and needs to be consulted separately.

## Species Maps Aggregation

The species maps are then aggregated to ...


## Clustering

To analyze the scenarios, the species maps are clustered to ...
The code for this step can be found in the separate repository
[reponame](https://github.com/blenback/reponame).
These scripts are adapted to the case of Switzerland and the Future-EI project.
...
