# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-08-28 17:25:15
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

def Focal1(Input_folder_contains_raster_s_to_compute_focal_statistics_on_="C:\\Users\\bblack\\switchdrive\\git\\Future-EI\\src\\habitat_map\\data_preparated\\wsl2", Output_folder="C:\\Users\\bblack\\switchdrive\\git\\Future-EI\\src\\habitat_map\\data_preparated\\test"):  # Focal statistics 6 radius (FUTURE_EI)

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    # Model Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\bblack\switchdrive\ArcGIS\Projects\habitat_map_sweco\habitat_map_sweco.gdb", workspace=r"C:\Users\bblack\switchdrive\ArcGIS\Projects\habitat_map_sweco\habitat_map_sweco.gdb"):

        for Raster_input, Name in #  NOT  IMPLEMENTED(Input_folder_contains_raster_s_to_compute_focal_statistics_on_, "", "TIF", "NOT_RECURSIVE"):

            # Process: Focal Statistics 5000 (Focal Statistics) (sa)
            Name = "ch_lulc_wslhabmap_pixel_gr11"
            _5000_Name_ = fr"{arcpy.env.workspace}\5000_{Name}"
            Focal_Statistics_5000 = _5000_Name_
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kuelling\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb", workspace=Output_folder):
                _5000_Name_ = arcpy.sa.FocalStatistics(in_raster=Raster_input, neighborhood="Circle 5000 MAP", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
                _5000_Name_.save(Focal_Statistics_5000)


            # Process: Focal Statistics 3000 (Focal Statistics) (sa)
            _3000_Name_ = fr"{arcpy.env.workspace}\3000_{Name}"
            Focal_Statistics_3000 = _3000_Name_
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kuelling\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb", workspace=Output_folder):
                _3000_Name_ = arcpy.sa.FocalStatistics(in_raster=Raster_input, neighborhood="Circle 3000 MAP", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
                _3000_Name_.save(Focal_Statistics_3000)


            # Process: Focal Statistics 1000 (Focal Statistics) (sa)
            _1000_Name_ = fr"{arcpy.env.workspace}\1000_{Name}"
            Focal_Statistics_1000 = _1000_Name_
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kuelling\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb", workspace=Output_folder):
                _1000_Name_ = arcpy.sa.FocalStatistics(in_raster=Raster_input, neighborhood="Circle 1000 MAP", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
                _1000_Name_.save(Focal_Statistics_1000)


            # Process: Focal Statistics 500 (Focal Statistics) (sa)
            _500_Name_ = fr"{arcpy.env.workspace}\500_{Name}"
            Focal_Statistics_500 = _500_Name_
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kuelling\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb", workspace=Output_folder):
                _500_Name_ = arcpy.sa.FocalStatistics(in_raster=Raster_input, neighborhood="Circle 500 MAP", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
                _500_Name_.save(Focal_Statistics_500)


            # Process: Focal Statistics 100 (Focal Statistics) (sa)
            _100_Name_ = fr"{arcpy.env.workspace}\100_{Name}"
            Focal_Statistics_100 = _100_Name_
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kuelling\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb", workspace=Output_folder):
                _100_Name_ = arcpy.sa.FocalStatistics(in_raster=Raster_input, neighborhood="Circle 100 MAP", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
                _100_Name_.save(Focal_Statistics_100)


            # Process: Focal Statistics 25 (Focal Statistics) (sa)
            _25_Name_ = fr"{arcpy.env.workspace}\25_{Name}"
            Focal_Statistics_25 = _25_Name_
            with arcpy.EnvManager(scratchWorkspace=r"C:\Users\kuelling\Documents\ArcGIS\Projects\MyProject7\MyProject7.gdb", workspace=Output_folder):
                _25_Name_ = arcpy.sa.FocalStatistics(in_raster=Raster_input, neighborhood="Circle 25 MAP", statistics_type="MEAN", ignore_nodata="DATA", percentile_value=90)
                _25_Name_.save(Focal_Statistics_25)


if __name__ == '__main__':
    Focal1(*argv[1:])
