# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Wed Oct 20 16:21:06 2021
# Model: Hydropower Water Yield
# This script specifies the arguments for the InVEST Hydropower Water Yield
# model and then runs it.

import natcap.invest.hydropower.hydropower_water_yield
import yaml, os

# Load the parameters from ../40_NCPs_params.yml (relative to this file)
with open(os.path.join(os.path.dirname(__file__), '..',
                       '40_NCPs_params.yml')) as stream:
    params = yaml.safe_load(stream)

print("InVEST WY model : initiated")
args = {
    'biophysical_table_path': params['WY']['biophysical_table_path'],
    'depth_to_root_rest_layer_path': params['data']['depth_to_root_rest_layer'],
    'do_scarcity_and_valuation': params['WY']['do_scarcity_and_valuation'],
    'eto_path': params['data']['eto'],
    'lulc_path': params['data']['lulcc2018'],
    'pawc_path': params['data']['pawc'],
    'precipitation_path': params['data']['precipitation'],
    'results_suffix': params['WY']['results_suffix'],
    'seasonality_constant': params['WY']['seasonality_constant'],
    'sub_watersheds_path': params['data']['sub_watersheds'],
    'watersheds_path': params['data']['watersheds'],
    'workspace_dir': params['paths']['workspace_dir'],
}

print("...starting")

if __name__ == '__main__':
    natcap.invest.hydropower.hydropower_water_yield.execute(args)
