# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Thu Jun  3 12:44:55 2021
# Model: Habitat Quality
# -----------------------------------------------
# This script runs the Habitat Quality model from InVEST. Nothing else is
# done except to define the parameters and input files, and then run the model.

import yaml, os

# Load the parameters from ../40_NCPs_params.yml (relative to this file)
with open(os.path.join(os.path.dirname(__file__), '..',
                       '40_NCPs_params.yml')) as stream:
    params = yaml.safe_load(stream)

import natcap.invest.habitat_quality

print("InVEST Habitat model : initiated")
args = {
    # This dictionary contains the input parameters required to run the NDR
    # model. Each key-value pair specifies a parameter and its corresponding
    # value.
    'half_saturation_constant': params['HAB']['half_saturation_constant'],
    'lulc_cur_path': params['HAB']['lulcc2018'],
    'results_suffix': '_18',
    'sensitivity_table_path': params['HAB']['sensitivity_table_path'],
    'threat_raster_folder': params['HAB']['threat_raster_folder'],
    'threats_table_path': params['HAB']['threats_table_path'],
    'workspace_dir': params['HAB']['workspace_dir'],
}
print("starting...")

# Executing Model calculation
if __name__ == '__main__':
    natcap.invest.habitat_quality.execute(args)

print("...done!")
