# --------------------------------------------- #
# Central config file for the Future-EI project #
# --------------------------------------------- #

# Bash variables
bash_variables:
  FUTURE_EI_LOG_LEVEL: debug
  FUTURE_EI_CONFIG_FILE: ~/Future-EI/src/config.yml
  FUTURE_EI_OUTPUT_DIR: ~/Future-EI-Output
  # Output Directories are relative to the $FUTURE_EI_OUTPUT_DIR
  LULCC_CH_OUTPUT_BASE_DIR: /lulcc_output # Location of all scenario folders, named by IDs
  # LULCC Check
  CHECK_LULCC_OUTPUT_DIR: /lulcc_check
  # Focal Prep
  FOCAL_OUTPUT_BASE_DIR: /focal_output
  # NCP
  NCP_OUTPUT_BASE_DIR: /ncp_output
  NCP_SCRATCH_BASE_DIR: /ncp_scratch
  # NSDM
  NSDM_OUTPUT_BASE_DIR: /nsdm_outputs
  # Species Aggregation
  SPAGG_OUTPUT_BASE_DIR: /spagg_output

  SIM_ID: # simulation id, can be used to look up in control table, set automatically
  # Variables for the docker container
  LULCC_DOCKER_NAMESPACE: cbueth
  LULCC_DOCKER_REPO: lulcc
  LULCC_DOCKER_VERSION: 0.3.0
  # Dinamica
  # UNCONDITIONAL=0, ERROR=1, WARNING=2, RESULT=3,
  # INFO=4, INFO2=5, DEBUG=6, DEBUG2=7
  DINAMICA_EGO_CLI_LOG_LEVEL: 7
  # LULCC HPC version
  LULCC_CH_HPC_DIR: ~/LULCC_CH_HPC
  # Model Variables - from LULCC_CH_HPC root
  LULCC_M_CLASS_AGG: Tools/LULC_class_aggregation.xlsx
  LULCC_M_SPEC: Tools/Model_specs.csv
  LULCC_M_PARAM_GRID: Tools/param-grid.xlsx
  LULCC_M_PRED_TABLE: Tools/Predictor_table.xlsx
  LULCC_M_REF_GRID: Data/Ref_grid.tif
  LULCC_M_CAL_PARAM_DIR: Data/Allocation_parameters/Calibration
  LULCC_M_SIM_PARAM_DIR: Data/Allocation_parameters/Simulation
  LULCC_M_RATE_TABLE_DIR: Data/Transition_tables/prepared_trans_tables
  LULCC_M_SIM_CONTROL_TABLE: ~/LULCC_CH_HPC/Tools/Simulation_control.csv
  LULCC_M_SPAT_INTS_TABLE: Tools/Spatial_interventions.csv
  LULCC_M_EI_INTS_TABLE: Tools/EI_interventions.csv
  LULCC_M_SCENARIO_SPEC: Tools/Scenario_specs.csv
  LULCC_M_EI_LAYER_DIR: Data/EI_intervention_layers
  LULCC_M_REMOVE_PRED_PROB_MAPS: True # remove prediction probability maps after
  # simulation if 1, True or TRUE
  # NCP variables
  NCP_PARAMS_YML: ~/Future-EI/src/steps/40_NCPs/NCP_models/40_NCPs_params.yml
  NCP_RUN_SCENARIO_ID: # Scenario ID, automatically set for each configuration
  NCP_RUN_YEAR: # Year for which to run NCPs, automatically set
  NCP_RUN_OUTPUT_DIR: # Output directory for NCPs, automatically set
  NCP_RUN_SCRATCH_DIR: # Scratch directory for NCPs, automatically set
  # Apptainer variables for the apptainer container
  APPTAINER_CONTAINERDIR: ~/apptainer_containers
  APPTAINER_CACHEDIR: /scratch/apptainer_cache
  # Overwrites $TMPDIR if not set by the system. $TMPDIR is used by Dinamica EGO.
  # and conda/libmamba
  ALTERNATIVE_TMPDIR: /scratch

# Focal LULC
FocalLULCC:
  WorkDir: ~/Future-EI/
  HistoricalDir:
  InputDir: /scratch/focal_lulcc/in
  OutputDir: /scratch/focal_lulcc/out
  BaseName: ch_lulc_agg11_present_pixel
  RadiusList: [ 100, 200, 500, 1500, 3000 ]
  WindowType: circle
  FocalFunction: mean
  Parallel: True
  NWorkers: 0  # 0 means use all available cores
  
# LULC check
CheckLULCC:
  InputDir:
  OutputDir:
  BaseName: LULCC_intensity_analysis
  Parallel: True
  NWorkers: 0  # 0 means use all available cores

