# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Tue Nov  1 11:05:28 2022
# Model: Crop Pollination
# -----------------------------------------------
# This script runs the Crop Pollination model from InVEST. Nothing else is done except to define the parameters and input files, and then run the model.

import sys
from os.path import join, dirname

import natcap.invest.pollination

sys.path.append(join(dirname(__file__), '..'))
from load_params import load_params

params = load_params(
    check_params=[
        ['run_params', 'NCP_RUN_SCENARIO_ID'],
        ['run_params', 'NCP_RUN_YEAR'],
        ['run_params', 'NCP_RUN_SCRATCH_DIR'],
        ['data', 'lulc'],
        ['POL', 'farm_vector_path'],
        ['POL', 'guild_table_path'],
        ['POL', 'landcover_biophysical_table_path'],
    ]
)

args = {
    # This dictionary contains the input parameters required to run the NDR model.
    # Each key-value pair specifies a parameter and its corresponding value.
    'landcover_raster_path': params['data']['lulc'],
    'farm_vector_path': params['POL']['farm_vector_path'],
    'guild_table_path': params['POL']['guild_table_path'],
    'landcover_biophysical_table_path': params['POL'][
        'landcover_biophysical_table_path'],
    'workspace_dir': join(
        params['run_params']['NCP_RUN_SCRATCH_DIR'],
        params['run_params']['NCP_RUN_SCENARIO_ID'],
        'POL',
        params['run_params']['NCP_RUN_YEAR']),
}

# Executing Model calculation
if __name__ == '__main__':
    print("POL: Starting Crop Pollination model...")
    natcap.invest.pollination.execute(args)
    print("POL: ...done!")
