# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.9 on Tue Nov  1 11:05:28 2022
# Model: Crop Pollination
# -----------------------------------------------
# This script runs the Crop Pollination model from InVEST. Nothing else is done except to define the parameters and input files, and then run the model.

import natcap.invest.pollination
import yaml, os

# Load the parameters from ../40_NCPs_params.yml (relative to this file)
with open(os.path.join(os.path.dirname(__file__), '..',
                       '40_NCPs_params.yml')) as stream:
    params = yaml.safe_load(stream)

args = {
    # This dictionary contains the input parameters required to run the NDR model.
    # Each key-value pair specifies a parameter and its corresponding value.
    'farm_vector_path': params['POL']['farm_vector_path'],
    'guild_table_path': params['POL']['guild_table_path'],
    'landcover_biophysical_table_path': params['POL'][
        'landcover_biophysical_table_path'],
    'landcover_raster_path': params['data']['landcover_raster_path'],
    'results_suffix': params['POL']['results_suffix'],
    'workspace_dir': params['global']['workspace_dir'],
}

# Executing Model calculation
if __name__ == '__main__':
    natcap.invest.pollination.execute(args)
