on:
  workflow_dispatch:
  push:
    paths:
      - 'src/steps/20_FocalLULC/20_FocalPrep_setup.sh'
      - 'src/steps/20_FocalLULC/20_FocalPrep_requirements.txt'
      - 'src/steps/40_NCPs/40_NCPs_setup.sh'
      - 'src/steps/40_NCPs/40_NCPs_requirements.txt'
  pull_request:

name: "Build Environments"

# test with matrix that tests conda, mamba and micromamba

jobs:
  build:
    name: "${{ matrix.setup_script.name }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setup_script:
          - name: 20_FocalPrep
            path: src/steps/20_FocalLULC/20_FocalPrep_setup.sh
          - name: 40_NCPs
            path: src/steps/40_NCPs/40_NCPs_setup.sh
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup mamba"
        uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge
      - name: "Setup Environment (${{ matrix.setup_script.name }})"
        run: |
          chmod +x ${{ matrix.setup_script.path }}
          ./${{ matrix.setup_script.path }}
