on:
  workflow_dispatch:
  push:
#    - '**/*_setup.sh'
#    - '**/*_requirements.txt'
#    paths:
##      - 'src/steps/10_LULCC/10_land_use_setup.sh'
##      - 'src/steps/10_LULCC/10_land_use_requirements.txt'
#      - 'src/steps/40_NCPs/40_NCPs_setup.sh'
#      - 'src/steps/40_NCPs/40_NCPs_requirements.txt'
  pull_request:

name: "Build Environments"

# test with matrix that tests conda, mamba and micromamba

jobs:
  build:
    name: "${{ matrix.conda_type.name }}: ${{ matrix.setup_script }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        setup_script: ['src/steps/40_NCPs/40_NCPs_setup.sh']
        conda_type:
          - name: conda
            with:
              auto-update-conda: true
          - name: miniforge
            with:
              miniforge-version: latest
              use-mamba: true
          - name: mamba
            with:
              mamba-version: "*"
              channels: conda-forge,defaults
              channel-priority: true
          - name: micromamba
        exclude:
          - setup_script: 'src/steps/40_NCPs/40_NCPs_setup.sh'
            conda_type:
              name: conda
              with:
                auto-update-conda: true

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup ${{ matrix.conda_type.name }}"
        uses: conda-incubator/setup-miniconda@v2
        with: ${{ matrix.conda_type.with }}
        if: matrix.conda_type.name != 'micromamba'
      - name: "Setup micromamba"
        uses: mamba-org/setup-micromamba@v1
        if: matrix.conda_type.name == 'micromamba'
      - name: "Setup Environment (${{ matrix.setup_script }})"
        run: |
          chmod +x ${{ matrix.setup_script }}
          ./${{ matrix.setup_script }}
