on:
  push:
    paths:
      - '**/*.sh'
  pull_request:

name: "Run Bash Tests"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testfile: [ test_get_rows.sh ]
    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ matrix.testfile }}
        run: cd tests && bash ${{ matrix.testfile }}